### ISSUE TITLE
Question: Basic theory for generating strained cells

### ISSUE THREAD

**Issue by m3lab-zzl** [libAtoms/matscipy#105]
Hi, `matscipy` is a fantastic work, really love it. 

But I got a question when generating the strained configuration:

In `elasticity.py/generate_strained_configs` function:

```py
T = np.eye(3) + Voigt_6_to_full_3x3_strain(strain)
at.set_cell(np.dot(T, at.cell.T).T, scale_atoms=False)
at.positions[:] = np.dot(T, at.positions.T).T
at.info['strain'] = T - np.eye(3)
```

I wonder why the new cell is generated in that way, is there any underlying theory? `np.dot(T, at.cell.T).T` seems to be equivalent to a simpler form of `np.dot(T, at.cell)` 

Thank you very much.

**Comment by jameskermode** [comment]
The transpose are needed because the [ASE cell](https://wiki.fysik.dtu.dk/ase/ase/cell.html#ase.cell.Cell) is stored row-wise rather than column-wise. Once that has been corrected for, we apply the transformation, then transpose back again to match the ASE convention.

**Comment by m3lab-zzl** [comment]
My mistake, `np.dot(T, at.cell.T).T` actually equals `np.dot(at.cell, T)`, not `np.dot(T, at.cell)`, here is a simple test:
```py
from ase.build import bulk
from ase.build import rotate
import numpy as np

cu = bulk('Cu', cubic=True)
xz_shear_strain = np.array([
    [0, 0, 0.01],
    [0, 0, 0],
    [0.01, 0, 0]
])
T = np.eye(3) + xz_shear_strain
print(cu.cell)
print(np.dot(cu.cell, T))
print(np.dot(T, cu.cell))
print(np.dot(T, cu.cell.T).T)

print('\n Rotated cell:')
t = [1, 1, -2]
n = [1, 1, 1]
x = [1, 0, 0]
z = [0, 0, 1]
rotate(cu, t, z, n, x)
print(cu.cell)
print(np.dot(cu.cell, T))
print(np.dot(T, cu.cell))
print(np.dot(T, cu.cell.T).T)
cu.set_cell(np.dot(T, cu.cell.T).T, scale_atoms=False)
print(cu.cell)
# if set cell using np.dot(cu.cell, T)
cu = bulk('Cu', cubic=True)
rotate(cu, t, z, n, x)
cu.set_cell(np.dot(cu.cell, T), scale_atoms=False)
print(cu.cell)
```

The result is:

```txt
Cell([3.61, 3.61, 3.61])
[[3.61   0.     0.0361]
 [0.     3.61   0.    ]
 [0.0361 0.     3.61  ]]
[[3.61   0.     0.0361]
 [0.     3.61   0.    ]
 [0.0361 0.     3.61  ]]
[[3.61   0.     0.0361]
 [0.     3.61   0.    ]
 [0.0361 0.     3.61  ]]

 Rotated cell:
Cell([[2.0842344717745487, 2.5526554800834362, 1.4737763285745453], [2.0842344717745487, -2.5526554800834362, 1.4737763285745453], [2.0842344717745482, 3.7591070062267513e-16, -2.9475526571490906]])
[[ 2.09897224e+00  2.55265548e+00  1.49461867e+00]
 [ 2.09897224e+00 -2.55265548e+00  1.49461867e+00]
 [ 2.05475895e+00  3.75910701e-16 -2.92671031e+00]]
[[ 2.10507682  2.55265548  1.4443008 ]
 [ 2.08423447 -2.55265548  1.47377633]
 [ 2.10507682  0.02552655 -2.93281489]]
[[ 2.09897224e+00  2.55265548e+00  1.49461867e+00]
 [ 2.09897224e+00 -2.55265548e+00  1.49461867e+00]
 [ 2.05475895e+00  3.75910701e-16 -2.92671031e+00]]
Cell([[2.098972235060294, 2.5526554800834362, 1.4946186732922908], [2.098972235060294, -2.5526554800834362, 1.4946186732922908], [2.0547589452030572, 3.7591070062267513e-16, -2.926710312431345]])
Cell([[2.098972235060294, 2.5526554800834362, 1.4946186732922908], [2.098972235060294, -2.5526554800834362, 1.4946186732922908], [2.0547589452030572, 3.7591070062267513e-16, -2.926710312431345]])
```

That means the following equation applies, which I still cannot figure out:

![image](https://user-images.githubusercontent.com/102862066/192488051-1b98992c-b72c-4883-9425-31a004ddc06f.png)

Here, xyz is the new cell, abc the old one, and e11~e33 is the strain tensor.

**Comment by m3lab-zzl** [comment]
I think I have made it out, and I will close this issue.

For future visitors, hint: 
Taking single vector x to analyze and then combine all 3 vectors, things will be much easier.

Cheers.
